// GENERATED by scripts/gen_site_commands.py from hotpath/cli.py's parser. Do not edit by hand:
// run `python scripts/gen_site_commands.py` after changing a command. A test fails if this drifts.

export type CliArg = { flag: string; help: string };
export type CliCommand = { name: string; summary: string; usage: string; args: CliArg[] };

export const CLI_COMMANDS: CliCommand[] = [
  {
    "name": "doctor",
    "summary": "check Git, Docker, credentials, and CUDA/ROCm/XPU/MPS availability",
    "usage": "hotpath doctor [options]",
    "args": [
      {
        "flag": "--json",
        "help": "print the report as JSON"
      },
      {
        "flag": "--require-gpu",
        "help": "fail unless PyTorch can use CUDA, ROCm, Intel XPU, or Apple MPS"
      },
      {
        "flag": "--verify-keys",
        "help": "ask each model endpoint whether its key still works (a present key can be revoked)"
      }
    ]
  },
  {
    "name": "init",
    "summary": "set a repository up for Hotpath (.hotpath.yaml + CI check)",
    "usage": "hotpath init [path] [options]",
    "args": [
      {
        "flag": "[path]",
        "help": "repository to set up (default: the current directory)"
      },
      {
        "flag": "--test-cmd TEST_CMD",
        "help": "command that checks correctness (exit 0 = correct)"
      },
      {
        "flag": "--bench-cmd BENCH_CMD",
        "help": "command that prints Hotpath benchmark JSON"
      },
      {
        "flag": "--profile-cmd PROFILE_CMD",
        "help": "command that prints a Hotpath profile (optional)"
      },
      {
        "flag": "--editable EDITABLE",
        "help": "comma-separated globs Hotpath may edit (default: *.py, or src/*.py)"
      },
      {
        "flag": "--lock LOCK",
        "help": "an extra glob Hotpath must never edit (repeatable)"
      },
      {
        "flag": "--execution {local,docker}",
        "help": "where candidate code runs"
      },
      {
        "flag": "--planner {openai,mock}",
        "help": "model that proposes hypotheses"
      },
      {
        "flag": "--worker {openai,baseten,mock}",
        "help": "model that writes each patch"
      },
      {
        "flag": "--mock-patches MOCK_PATCHES",
        "help": "directory of recorded patches for offline `--provider mock` runs"
      },
      {
        "flag": "--name NAME",
        "help": "name shown in reports (default: the directory name)"
      },
      {
        "flag": "-y, --yes",
        "help": "accept detected defaults without prompting"
      },
      {
        "flag": "--force",
        "help": "overwrite an existing .hotpath.yaml and workflow"
      },
      {
        "flag": "--no-workflow",
        "help": "do not write the GitHub Actions check"
      }
    ]
  },
  {
    "name": "go",
    "summary": "one command: assess a repo, build and test it, find a benchmark, optimize, and open a draft PR",
    "usage": "hotpath go [target] [options]",
    "args": [
      {
        "flag": "[target]",
        "help": "GitHub URL, owner/repo, any git URL, or a local checkout (default: the current directory)"
      },
      {
        "flag": "-y, --yes",
        "help": "accept every default: local execution consent, the benchmark, and pushing the PR branch"
      },
      {
        "flag": "--provider {openai,mock}",
        "help": "model provider (default: openai; mock is offline)"
      },
      {
        "flag": "--mock-patches MOCK_PATCHES",
        "help": "recorded patches for --provider mock"
      },
      {
        "flag": "--iterations ITERATIONS",
        "help": "search iterations (default: 3)"
      },
      {
        "flag": "--candidates CANDIDATES",
        "help": "candidates per iteration"
      },
      {
        "flag": "--beam BEAM",
        "help": "beam width: accepted heads kept per iteration (1 = greedy)"
      },
      {
        "flag": "--max-tokens MAX_TOKENS",
        "help": "stop the search once model calls have used this many tokens"
      },
      {
        "flag": "--max-minutes MAX_MINUTES",
        "help": "stop the search after this many minutes"
      },
      {
        "flag": "--sandbox {auto,local,docker}",
        "help": "where the target's code runs (auto: Docker if it is running, else local with consent)"
      },
      {
        "flag": "--test-cmd TEST_CMD",
        "help": "override the detected correctness check"
      },
      {
        "flag": "--bench-cmd BENCH_CMD",
        "help": "use this benchmark (prints Hotpath JSON) instead of finding or generating one"
      },
      {
        "flag": "--no-generate",
        "help": "never ask a model to write a benchmark"
      },
      {
        "flag": "--reuse-benchmark, --no-reuse-benchmark",
        "help": "measure against the same generated benchmark as the last run on this repository, re-validated before use (default: on; without it two runs are not comparable)"
      },
      {
        "flag": "--regenerate-benchmark",
        "help": "write a new benchmark even if the remembered one still validates"
      },
      {
        "flag": "--test-runs TEST_RUNS",
        "help": "baseline test runs used to detect flaky tests"
      },
      {
        "flag": "--test-timeout TEST_TIMEOUT",
        "help": "seconds per test-suite run"
      },
      {
        "flag": "--no-pr",
        "help": "build the PR branch locally but do not push"
      },
      {
        "flag": "--pr-method {auto,gh,token,link}",
        "help": "how to open the PR: gh CLI, GITHUB_TOKEN, or a pre-filled link (auto tries them in order)"
      },
      {
        "flag": "--ready",
        "help": "open the PR ready for review instead of as a draft"
      },
      {
        "flag": "--no-open",
        "help": "do not open the PR or dashboard in a browser"
      },
      {
        "flag": "--dashboard, --no-dashboard",
        "help": "serve the live dashboard during the search and keep it up afterwards (default: on)"
      },
      {
        "flag": "--verify-ci, --no-verify-ci",
        "help": "after opening the PR, wait for the repository's CI and fix what the PR broke (default: on; failures already present on the base are never touched)"
      },
      {
        "flag": "--ci-attempts CI_ATTEMPTS",
        "help": "how many times to try repairing CI"
      },
      {
        "flag": "--ci-timeout CI_TIMEOUT",
        "help": "seconds to wait for CI checks to settle"
      },
      {
        "flag": "--port PORT",
        "help": "dashboard port (default: 8765)"
      },
      {
        "flag": "--workspaces WORKSPACES",
        "help": "where clones and per-repo environments live (default: ./workspaces)"
      },
      {
        "flag": "--remote REMOTE",
        "help": "git remote to push the PR branch to (default: origin)"
      },
      {
        "flag": "--resume",
        "help": "continue the last `go` run on this repository"
      }
    ]
  },
  {
    "name": "check",
    "summary": "preflight a repository in seconds: what would stop a run, and what it would cost (exit 0 go, 1 caution, 2 stop)",
    "usage": "hotpath check [path] [options]",
    "args": [
      {
        "flag": "[path]",
        "help": "local path or GitHub URL (default: the current directory)"
      },
      {
        "flag": "--json",
        "help": "print the findings as JSON"
      },
      {
        "flag": "--iterations ITERATIONS",
        "help": "iterations to price the estimate for"
      },
      {
        "flag": "--candidates CANDIDATES",
        "help": "candidates per iteration to price for"
      }
    ]
  },
  {
    "name": "assess",
    "summary": "read-only report: ecosystem, tests, benchmark, editable and locked files",
    "usage": "hotpath assess [path] [options]",
    "args": [
      {
        "flag": "[path]",
        "help": "repository to inspect (default: the current directory)"
      },
      {
        "flag": "--json",
        "help": "print the report as JSON"
      }
    ]
  },
  {
    "name": "run",
    "summary": "run the optimization loop once",
    "usage": "hotpath run [config] [options]",
    "args": [
      {
        "flag": "[config]",
        "help": "config file (default: the nearest .hotpath.yaml)"
      },
      {
        "flag": "--iterations ITERATIONS",
        "help": "override search.iterations from the config"
      },
      {
        "flag": "--beam BEAM",
        "help": "beam width: how many accepted heads to keep and expand each iteration (1 = greedy)"
      },
      {
        "flag": "--provider {mock,openai}",
        "help": "override both planner and worker providers"
      },
      {
        "flag": "--export EXPORT",
        "help": "directory to write the best accepted source tree into"
      },
      {
        "flag": "--autocommit",
        "help": "snapshot uncommitted changes in the target into a commit before measuring (default: refuse)"
      },
      {
        "flag": "--resume RUN_ID",
        "help": "continue a stopped or failed run from its stored beam instead of re-measuring a baseline; runs up to the larger of its original budget and --iterations"
      },
      {
        "flag": "--pr",
        "help": "when the run finishes with a win, push a branch and open a pull request"
      },
      {
        "flag": "--base BASE",
        "help": "branch the PR targets (default: the branch the run measured)"
      },
      {
        "flag": "--remote REMOTE",
        "help": "git remote to push the PR branch to (default: origin)"
      },
      {
        "flag": "--draft",
        "help": "open the PR as a draft"
      },
      {
        "flag": "--pr-method {auto,gh,token,link}",
        "help": "how to open the PR: gh CLI, GITHUB_TOKEN, or a pre-filled link (auto tries them in order)"
      },
      {
        "flag": "--allow-moved-base",
        "help": "publish even though the base branch moved since the run measured it"
      }
    ]
  },
  {
    "name": "pr",
    "summary": "publish a finished run as a pull request (one verified commit per change)",
    "usage": "hotpath pr [config] [options]",
    "args": [
      {
        "flag": "[config]",
        "help": "config file (default: the nearest .hotpath.yaml)"
      },
      {
        "flag": "--run-id RUN_ID",
        "help": "which run to publish (defaults to the latest)"
      },
      {
        "flag": "--prune",
        "help": "ablate first and ship the verified pruned stack if there is one"
      },
      {
        "flag": "--no-push",
        "help": "only build the local branch hotpath/<run id>"
      },
      {
        "flag": "--base BASE",
        "help": "branch the PR targets (default: the branch the run measured)"
      },
      {
        "flag": "--remote REMOTE",
        "help": "git remote to push the PR branch to (default: origin)"
      },
      {
        "flag": "--draft",
        "help": "open the PR as a draft"
      },
      {
        "flag": "--pr-method {auto,gh,token,link}",
        "help": "how to open the PR: gh CLI, GITHUB_TOKEN, or a pre-filled link (auto tries them in order)"
      },
      {
        "flag": "--allow-moved-base",
        "help": "publish even though the base branch moved since the run measured it"
      }
    ]
  },
  {
    "name": "serve",
    "summary": "serve the dashboard (and allow starting runs from it)",
    "usage": "hotpath serve [config] [options]",
    "args": [
      {
        "flag": "[config]",
        "help": "config file; without one (and with --db) the dashboard is read-only"
      },
      {
        "flag": "--db DB",
        "help": "database path (defaults to the config's)"
      },
      {
        "flag": "--host HOST",
        "help": "loopback address to bind (non-loopback is refused)"
      },
      {
        "flag": "--port PORT",
        "help": "port (default: 8765)"
      }
    ]
  },
  {
    "name": "ablate",
    "summary": "re-measure the accepted chain with each change removed",
    "usage": "hotpath ablate [config] [options]",
    "args": [
      {
        "flag": "[config]",
        "help": "config file (default: the nearest .hotpath.yaml)"
      },
      {
        "flag": "--run-id RUN_ID",
        "help": "which run to ablate (defaults to the latest)"
      },
      {
        "flag": "--json JSON",
        "help": "write the report here"
      },
      {
        "flag": "--prune",
        "help": "also try dropping every change that did not pull its weight, together; keep the pruned stack only if it passes correctness and the full stack is not measurably faster"
      }
    ]
  },
  {
    "name": "export",
    "summary": "write a PR-ready bundle (optimized tree, diff, benchmark table, ablation)",
    "usage": "hotpath export config dest [options]",
    "args": [
      {
        "flag": "config",
        "help": "config file (use .hotpath.yaml for the current repository)"
      },
      {
        "flag": "dest",
        "help": "directory to write the bundle into"
      },
      {
        "flag": "--run-id RUN_ID",
        "help": "which run to export (defaults to the latest)"
      },
      {
        "flag": "--ablate",
        "help": "also run leave-one-out ablation and include the table (re-runs benchmarks)"
      },
      {
        "flag": "--prune",
        "help": "ablate, then export the pruned stack instead of the head if pruning is verified (implies --ablate)"
      }
    ]
  }
];
