"""Render the site's CLI reference from the real argparse parser, so the two cannot drift.

    python scripts/gen_site_commands.py          # rewrite site/src/data/commands.ts
    python scripts/gen_site_commands.py --check  # exit 1 if the file is stale (tests/test_site_commands.py does this)
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "site" / "src" / "data" / "commands.ts"

HEADER = """\
// GENERATED by scripts/gen_site_commands.py from hotpath/cli.py's parser. Do not edit by hand:
// run `python scripts/gen_site_commands.py` after changing a command. A test fails if this drifts.

export type CliArg = { flag: string; help: string };
export type CliCommand = { name: string; summary: string; usage: string; args: CliArg[] };

export const CLI_COMMANDS: CliCommand[] = """


def _flag(action: argparse.Action) -> str:
    if not action.option_strings:
        return action.dest if action.nargs is None else f"[{action.dest}]"
    flag = ", ".join(action.option_strings)
    if action.nargs == 0:
        return flag
    if action.choices:
        return f"{flag} {{{','.join(map(str, action.choices))}}}"
    return f"{flag} {action.metavar or action.dest.upper()}"


def commands() -> list[dict]:
    sys.path.insert(0, str(ROOT))
    from hotpath.cli import build_parser

    parser = build_parser()
    sub = next(a for a in parser._actions if isinstance(a, argparse._SubParsersAction))
    summaries = {c.dest: c.help or "" for c in sub._choices_actions}
    out = []
    for name, sp in sub.choices.items():
        actions = [a for a in sp._actions if not isinstance(a, argparse._HelpAction)]
        positionals = [_flag(a) for a in actions if not a.option_strings]
        usage = " ".join(["hotpath", name, *positionals] + (["[options]"] if any(a.option_strings for a in actions) else []))
        out.append({
            "name": name,
            "summary": " ".join(summaries.get(name, "").split()),
            "usage": usage,
            "args": [{"flag": _flag(a), "help": " ".join((a.help or "").split())} for a in actions],
        })
    return out


def render() -> str:
    return HEADER + json.dumps(commands(), indent=2, ensure_ascii=False) + ";\n"


def main() -> int:
    text = render()
    if "--check" in sys.argv[1:]:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current.replace("\r\n", "\n") != text:
            print(f"{OUT.relative_to(ROOT)} is stale: run `python scripts/gen_site_commands.py`")
            return 1
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
